# Generated by Django 2.0.5 on 2018-05-26 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180526_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.AddField(
            model_name='rooms',
            name='study_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
