# Generated by Django 2.0.5 on 2018-05-26 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180526_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(default=datetime.date.today)),
                ('room_size', models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8')])),
            ],
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
