# Generated by Django 2.0.5 on 2018-05-26 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180526_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(default=datetime.date.today)),
                ('room_size', models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8')])),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_size',
        ),
        migrations.RemoveField(
            model_name='room',
            name='study_date',
        ),
        migrations.AddField(
            model_name='room',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Date'),
        ),
    ]
